name: "Sending mail for faild wrokflows"

on:
 wrokflow_dispatch:
  

jobs:
 send-mail:
  runs-on: ubuntu:latest
  steps:
   - name: Chech out the repo
     uses: actions/checkout@v2

   - name: configure python
     uses: actions/setup-python@v2
     with:
      python-version: '3.11'
   
   - name: Install dependecies
     run: python -m pip install --upgrade pip

   - name: Send may mail
     run: python3 script.py
     env:
      WORKFLOW_NAME: ${{ github.workflow }}
      REPO_NAME: ${{ github.repository }}
      WORKFLOW_RUN_ID: ${{ github.run_id }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
      RECEIVER_MAIL: ${{ secrets.RECIEVER_MAIL }}
   
   
  